# DigitalOcean App Platform Specification
# This file defines the app structure for deployment

name: ctrlp-pos

# Region: Pick closest to your users
region: sgp  # Singapore (options: nyc, sfo, ams, sgp, lon, fra, tor, blr, syd)

services:
  # Laravel Backend API
  - name: api
    source_dir: /backend
    github:
      repo: YOUR_GITHUB_USERNAME/ctrlp-pos
      branch: main
      deploy_on_push: true
    
    # Use PHP buildpack
    build_command: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    
    run_command: php artisan migrate --force && heroku-php-nginx -C nginx.conf public/
    
    # Environment type
    environment_slug: php
    
    # HTTP Port
    http_port: 8080
    
    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 10
      period_seconds: 30
    
    # Environment variables (set in DO dashboard for secrets)
    envs:
      - key: APP_NAME
        value: "PrintShop POS"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: ${APP_URL}
      - key: APP_KEY
        type: SECRET
        value: ${APP_KEY}
      
      # Database (Supabase)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        type: SECRET
        value: ${DB_HOST}
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        type: SECRET
        value: ${DB_PASSWORD}
      
      # Session & Cache
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      
      # CORS
      - key: FRONTEND_URL
        value: ${FRONTEND_URL}

# Static Site for React Frontend
static_sites:
  - name: frontend
    source_dir: /frontend
    github:
      repo: YOUR_GITHUB_USERNAME/ctrlp-pos
      branch: main
      deploy_on_push: true
    
    build_command: npm ci && npm run build
    output_dir: dist
    
    # SPA routing configuration
    routes:
      - path: /
        preserve_path_prefix: false
    
    # Catch-all route for SPA
    catchall_document: index.html
    error_document: index.html
    
    # Environment variables
    envs:
      - key: VITE_API_BASE_URL
        value: ${API_URL}/api
